version: '2.3'

x-log-config: &log-config
  logging:
    driver: json-file
    options:
      max-size: "20m"
      max-file: "10"

services:
  node_exporter:
    env_file: .env
    image: quay.io/prometheus/node-exporter:v1.0.1
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
      - '--collector.textfile.directory=/data/'
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
      - ${DATA_DIR:-./data}/performance-analysis:/data:ro
    << : *log-config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metrics_node.rule=Host(`metrics.${SERVER_NAME}`)"
      - "traefik.http.routers.metrics_node.tls=true"
      - "traefik.http.routers.metrics_node.tls.certresolver=le"
      - "traefik.http.routers.metrics_node.middlewares=metrics_node-access-control@docker"
      - "traefik.http.middlewares.metrics_node-access-control.ipwhitelist.sourcerange=${CIDR_ALLOW_METRICS}"
      - "traefik.http.services.metrics_node.loadbalancer.server.port=9100"

  traefik:
    image: traefik:2.2
    restart: always
    env_file: .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./traefik:/etc/traefik
      - ${DATA_DIR:-./data}/traefik:/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: --certificatesResolvers.le.acme.email=contact@raiden.network
    healthcheck:
      disable: true
    << : *log-config
